In [1]:
import numpy as np

### 建立陣列array

In [2]:
d1 = np.array([1, 2, 3, 4, 5])

In [3]:
d2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

In [4]:
L = [1, 2, 3, 4, 5]
L

[1, 2, 3, 4, 5]

### 維度ndim

In [5]:
d2.ndim

2

### 數量shape

In [6]:
d2.shape

(2, 5)

In [7]:
d2.shape[0]

2

### 範圍range

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 全0矩陣

In [9]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### 全1矩陣

In [11]:
np.ones([5])

array([1., 1., 1., 1., 1.])

In [12]:
np.ones([5, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### 全n矩陣

In [13]:
np.ones([5, 2])-3

array([[-2., -2.],
       [-2., -2.],
       [-2., -2.],
       [-2., -2.],
       [-2., -2.]])

### List<=>Numpy

In [14]:
d1.tolist()

[1, 2, 3, 4, 5]

In [15]:
np.array(L)

array([1, 2, 3, 4, 5])

### 重塑reshape

In [16]:
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
data.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
data.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### 轉置

In [19]:
data = np.arange(12).reshape(4, 3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
data.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])