In [1]:
import numpy as np

In [2]:
data = np.random.randint(10, size=[5])
data

array([2, 3, 0, 1, 9])

### 排序sort

In [3]:
np.sort(data)

array([0, 1, 2, 3, 9])

In [4]:
np.sort(data)[::-1]

array([9, 3, 2, 1, 0])

### 位置排序argsort

In [5]:
np.argsort(data)

array([2, 3, 0, 1, 4], dtype=int64)

In [6]:
np.argsort(data)[::-1]

array([4, 1, 0, 3, 2], dtype=int64)

### 最大值位置

In [7]:
np.argmax(data)

4

### 最小值位置

In [8]:
np.argmin(data)

2