In [1]:
import numpy as np

In [2]:
Array = np.array([1, 2, 3])
Array

array([1, 2, 3])

In [3]:
List = [1, 2, 3]
List

[1, 2, 3]

### Python

In [4]:
List2 = List
List2

[1, 2, 3]

In [5]:
List2[0] = 7
List2

[7, 2, 3]

In [6]:
# List也被改了
List

[7, 2, 3]

In [7]:
# 應該這麼寫
List = [1, 2, 3]
List2 = List.copy()

List2[0] = 7

In [8]:
List

[1, 2, 3]

In [9]:
List2

[7, 2, 3]

### Numpy

In [10]:
Array2 = Array
Array2

array([1, 2, 3])

In [11]:
Array2[0] = 7
Array2

array([7, 2, 3])

In [12]:
# Array也被改了
Array

array([7, 2, 3])

In [13]:
# 應該這麼寫
Array = np.array([1, 2, 3])
Array2 = List.copy()

Array2[0] = 7

In [14]:
Array

array([1, 2, 3])

In [15]:
Array2

[7, 2, 3]